services:
  api:
    image: registry.cn-qingdao.aliyuncs.com/initium/panda-park:${ENVIRONMENT}
    platform: linux/amd64
    restart: on-failure
    build:
      context: .
      args:
        ENVIRONMENT: ${ENVIRONMENT}

    healthcheck: # 添加健康检测
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health-check" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s

  proxy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/frontend/www:/usr/src/dist
      - ./data/log:/data/log
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./ssl:/data/caddy/certificates