services:
  api:
    image: web-server
#    platform: linux/amd64
    restart: on-failure
    build:
      context: .
      args:
        ENVIRONMENT: ${ENVIRONMENT}

    healthcheck: # 添加健康检测
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health-check" ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s
